#!/bin/bash

# Print a pretty graph of the git log.

# Based on http://stackoverflow.com/a/1838938/199644
# and https://github.com/garybernhardt/dotfiles/blob/master/.githelpers

BLACK="%x1b[0m"
RED="%x1b[31m"
GREEN="%x1b[32m"
YELLOW="%x1b[33m"
RESET=$BLACK

HTAB="%x09"
SPACE="%x20"

SHA="${RED}%h${HTAB}"
REFS="${GREEN}%d${SPACE}"
SUBJECT="${BLACK}%s${SPACE}"
AUTHOR="${YELLOW}(%an)${RESET}"

FORMAT="${SHA}${REFS}${SUBJECT}${AUTHOR}"

git log --graph --pretty=tformat:$FORMAT --full-history --all $@
