#!/bin/bash

# Print a pretty graph of the git log.

# Based on http://stackoverflow.com/a/1838938/199644
# and https://github.com/garybernhardt/dotfiles/blob/master/.githelpers

AUTOCOLOR="%C(auto)"
RESET="%Creset"

HTAB="%x09"
SPACE="%x20"

SHA="%h${HTAB}"
REFS="%d${SPACE}"
SUBJECT="%s${SPACE}"
AUTHOR="%C(green)(%an)"

FORMAT="${AUTOCOLOR}${SHA}${REFS}${SUBJECT}${AUTHOR}${RESET}"

git log --graph --decorate --boundary --format="${FORMAT}" $@
