#!/bin/bash

# From http://stackoverflow.com/questions/1527234/finding-a-branch-point-with-git

# Find the first commit where one branch forked off of another. Since git
# merge-base will only show you the last commit when the branches merged,
# instead find the first difference between the first parents of both branches.
#
# From the documentation for the first parent option:
#
# Follow only the first parent commit upon seeing a merge commit. This option
# can give a better overview when viewing the evolution of a particular topic
# branch, because merges into a topic branch tend to be only about adjusting to
# updated upstream from time to time, and this option allows you to ignore the
# individual commits brought in to your history by such a merge.

zsh -c 'diff --old-line-format='' --new-line-format='' <(git rev-list --first-parent "${1:-master}") <(git rev-list --first-parent "${2:-HEAD}") | head -1' -
