#!/bin/bash

# Make any directory a server.

function open-when-ready() {
  PORT=${1-8000}
  if [[ $PORT =~ ^[0-9]+$ ]]; then
    while true; do
      lsof -i :$PORT > /dev/null
      if [[ $? == 0 ]]; then
        open http://localhost:$PORT
        break
      fi
    done
  fi
}

(open-when-ready $@ &)
python -m SimpleHTTPServer $@
