#!/bin/bash

# Make any directory a server.

function open-when-ready() {
  port=${1-8000}
  while true; do
    lsof -i :$port > /dev/null
    if [[ $? == 0 ]]; then
      open http://localhost:$port
      break
    fi
  done
}

open-when-ready $@ &
python -m SimpleHTTPServer $@
