#!/bin/bash

# Make any directory a server.

function open-when-ready() {
  PORT=${1-8000}
  while true; do
    lsof -i :$PORT > /dev/null
    if [[ $? == 0 ]]; then
      open http://localhost:$PORT
      break
    fi
  done
}

open-when-ready $@ &
python -m SimpleHTTPServer $@
