#!/bin/bash -e

# Update Janus
(cd ~/.vim && rake)

# Update additional vim plugins
(cd ~/.janus && git submodule foreach 'git pull')

# Update Awesome-hammerspoon
#Disabled while configuration often breaks against updates
#(cd ~/.hammerspoon && git pull)

# Update anything installed with homebrew
(brew update && brew doctor && brew upgrade --all && brew cleanup)

# Update globally installed NPM utilities
(
  CURRENT_NPM=`npmrc | grep \* | awk '{print $2}'`;
  npmrc default;
  npm -g update;
  npmrc $CURRENT_NPM;
)

# Update Chromium
(brew cask install --force chromium)
