#!/bin/bash -e

# Update vim plugins
# https://tinyurl.com/y8o8mc9g
vim -S <(echo -e "PlugUpdate \n qa")

# Update Awesome-hammerspoon
#Disabled while configuration often breaks against updates
#(cd ~/.hammerspoon && git pull)

# Update anything installed with homebrew
(brew update && brew doctor && brew upgrade && brew cleanup)

# Update globally installed NPM utilities
(
  CURRENT_NPM=`npmrc | grep \* | awk '{print $2}'`;
  npmrc default;
  npm -g update;
  npmrc $CURRENT_NPM;
)

# Update Chromium
(brew cask install --force chromium)
